# Generated by Django 5.0.6 on 2025-11-08 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0004_remove_examtype_unique_examtype_per_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.examtype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.courses')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.term')),
            ],
            options={
                'ordering': ['subject__title'],
                'indexes': [models.Index(fields=['student', 'term', 'session', 'exam_type'], name='portal_resu_student_033a52_idx')],
                'unique_together': {('student', 'subject', 'exam_type', 'term', 'session')},
            },
        ),
    ]
