# Generated by Django 5.0.6 on 2025-11-22 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_result_portal_ca_score_and_more'),
        ('quiz', '0010_generationjob'),
        ('sms', '0004_remove_examtype_unique_examtype_per_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwriting', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('sports', models.IntegerField(default=0)),
                ('drawing_painting', models.IntegerField(default=0)),
                ('crafts', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('reliability', models.IntegerField(default=0)),
                ('neatness', models.IntegerField(default=0)),
                ('politeness', models.IntegerField(default=0)),
                ('honesty', models.IntegerField(default=0)),
                ('relationship_with_students', models.IntegerField(default=0)),
                ('self_control', models.IntegerField(default=0)),
                ('attentiveness', models.IntegerField(default=0)),
                ('perseverance', models.IntegerField(default=0)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.term')),
            ],
            options={
                'verbose_name': 'Student Behavior Record',
                'verbose_name_plural': 'Student Behavior Records',
                'unique_together': {('student', 'term', 'session')},
            },
        ),
    ]
