# Generated by Django 5.0.6 on 2025-11-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_studentbehaviorrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbehaviorrecord',
            options={},
        ),
    ]
