# Generated by Django 5.0.6 on 2025-11-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_studentbehaviorrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbehaviorrecord',
            name='form_teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbehaviorrecord',
            name='form_teacher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentbehaviorrecord',
            name='principal_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
