# Generated by Django 5.0.6 on 2025-11-22 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_remove_studentbehaviorrecord_form_teacher_name_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='form_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'form_teacher_role': 'form_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_behaviors', to='teacher.teacher'),
        ),
    ]
