# Generated by Django 5.0.6 on 2026-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_studentbehaviorrecord_form_teacher'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbehaviorrecord',
            name='form_teacher',
        ),
        migrations.AddField(
            model_name='studentbehaviorrecord',
            name='form_teacher',
            field=models.ManyToManyField(blank=True, related_name='behavior_records', to='teacher.teacher'),
        ),
    ]
