# Generated by Django 5.0.6 on 2026-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_result_portal_exam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='attendance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='attentiveness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='crafts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='drawing_painting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='games',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='handwriting',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='honesty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='neatness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='perseverance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='politeness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='punctuality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='relationship_with_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='reliability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='self_control',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentbehaviorrecord',
            name='sports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
