# Generated by Django 5.0.6 on 2026-03-18 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_studentbehaviorrecord_attendance_and_more'),
        ('quiz', '0018_alter_question_answer'),
        ('sms', '0007_alter_term_name'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentbehaviorrecord',
            index=models.Index(fields=['session', 'term'], name='portal_stud_session_880f08_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbehaviorrecord',
            index=models.Index(fields=['student', 'session', 'term'], name='portal_stud_student_a3beee_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbehaviorrecord',
            index=models.Index(fields=['school', 'session', 'term'], name='portal_stud_school__6504f3_idx'),
        ),
    ]
