# Generated by Django 5.0.6 on 2025-10-22 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ColumnLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_locked', models.BooleanField(default=False)),
                ('midterm_locked', models.BooleanField(default=False)),
                ('exam_locked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_obj',
            fields=[
                ('learning_objectives', models.TextField(blank=True, default='Input your learning objectives', null=True)),
                ('ai_question_num', models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='Number of AI Questions')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=35)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('learning_objectives', models.TextField(blank=True, default='Input your learning objectives', null=True)),
                ('ai_question_num', models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='Number of AI Questions')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_teacher_remark', models.CharField(blank=True, max_length=300)),
                ('form_teacher_role', models.CharField(choices=[('form_teacher', 'form_teacher'), ('not_form_teacher', 'Not Form Teacher')], default='not_form_teacher', max_length=50)),
                ('classes_taught', models.ManyToManyField(blank=True, related_name='teachers', to='quiz.coursegrade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='quiz.school')),
                ('subjects_taught', models.ManyToManyField(blank=True, related_name='teachers', to='quiz.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
