# Generated by Django 5.0.6 on 2024-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_course_unique_together'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='quiz.course'),
        ),
    ]
