# Generated by Django 5.0.6 on 2024-10-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        ('teacher', '0002_alter_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='sms.courses'),
        ),
    ]
