# Generated by Django 4.1 on 2024-04-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_remove_group_subjects_remove_student_email_and_more'),
        ('teacher', '0002_remove_teacher_address_remove_teacher_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='quiz.school'),
        ),
    ]
