# Generated by Django 5.0.6 on 2024-10-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_result_is_locked'),
        ('teacher', '0006_columnlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnlock',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='columnlock',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
