# Generated by Django 5.0.6 on 2025-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_course_options'),
        ('teacher', '0007_remove_columnlock_teacher_alter_columnlock_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='quiz.coursegrade'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learning_objectives',
            field=models.CharField(blank=True, default='Input your learning objectives', max_length=2000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='quiz.course'),
        ),
    ]
