# Generated by Django 5.0.6 on 2025-05-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_teacher_ai_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ai_question_num',
            field=models.PositiveIntegerField(blank=True, default=500, null=True, verbose_name='Number of AI Questions'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learning_objectives',
            field=models.CharField(blank=True, default='Input your learning objectives', max_length=2000, null=True),
        ),
    ]
