# Generated by Django 5.0.6 on 2024-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_samplecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ai_question_num',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
