# Generated by Django 5.0.6 on 2025-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_teacher_ai_question_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='learning_objectives',
            field=models.TextField(blank=True, default='Input your learning objectives', null=True),
        ),
    ]
