# Generated by Django 5.0.6 on 2024-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_teacher_ai_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='learning_objectives',
            field=models.CharField(blank=True, default='Input your learnig objectives', max_length=200),
        ),
    ]
