# Generated by Django 5.0.6 on 2024-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_teacher_learning_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form_teacher_role',
            field=models.CharField(choices=[('form_teacher', 'form_teacher'), ('not_form_teacher', 'Not Form Teacher')], default='not_form_teacher', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learning_objectives',
            field=models.CharField(blank=True, default='Input your learning objectives', max_length=200),
        ),
    ]
