# Generated by Django 5.0.6 on 2024-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_form_teacher_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form_teacher_remark',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
