# Generated by Django 5.0.6 on 2024-09-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_alter_courses_exam_type'),
        ('teacher', '0013_teacher_form_teacher_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='sms.courses'),
        ),
    ]
