# Generated by Django 5.0.6 on 2024-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_teacher_subjects_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='form_teacher_role',
            field=models.CharField(choices=[('form_teacher', 'Form Teacher'), ('not_form_teacher', 'Not Form Teacher')], default='not_form_teacher', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
