# Generated by Django 5.0.6 on 2024-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_alter_teacher_form_teacher_role_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='form_teacher_role',
            field=models.CharField(choices=[('form_teacher', 'form_teacher'), ('not_form_teacher', 'Not Form Teacher')], default='not_form_teacher', max_length=50),
        ),
    ]
