# Generated by Django 5.0.6 on 2025-10-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table='auth_user',
        ),
    ]
