# Generated by Django 5.0.6 on 2025-11-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
