# Generated by Django 5.0.6 on 2025-11-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='report_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
