# Generated by Django 5.0.6 on 2025-11-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_report_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='report_class',
        ),
    ]
