# Generated by Django 5.0.6 on 2025-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_newuser_report_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
