# Generated by Django 5.0.6 on 2024-06-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed_topics',
        ),
    ]
