# Generated by Django 5.0.6 on 2026-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0016_alter_question_answer_alter_question_id_and_more'),
        ('users', '0006_newuser_is_principal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newuser',
            index=models.Index(fields=['school', 'student_class'], name='auth_user_school__1ddcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='newuser',
            index=models.Index(fields=['school', 'student_class', 'username'], name='auth_user_school__002356_idx'),
        ),
        migrations.AddIndex(
            model_name='newuser',
            index=models.Index(fields=['email', 'username'], name='auth_user_email_9f0fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='newuser',
            index=models.Index(fields=['first_name', 'last_name'], name='auth_user_first_n_199799_idx'),
        ),
    ]
