# Generated by Django 5.0.6 on 2024-08-13 12:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_completed_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photos'),
        ),
    ]
