# Generated by Django 5.0.6 on 2024-08-13 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
