# Generated by Django 5.0.6 on 2026-03-18 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_auth_user_school__1ddcc1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='pro_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photos'),
        ),
    ]
