# Generated by Django 5.0.6 on 2026-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
    ]
