# Generated by Django 5.0.6 on 2024-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
