# Generated by Django 5.0.6 on 2024-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
