# Generated by Django 5.0.6 on 2024-08-13 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_image_url', max_length=255, null=True, verbose_name='profile_photos'),
        ),
    ]
