# Generated by Django 5.0.6 on 2024-08-13 14:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pro_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://i.ibb.co/cx34WCc/logo.png', max_length=255, null=True, verbose_name='profile_photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
