# Generated by Django 5.0.6 on 2024-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_newuser_pro_img_alter_profile_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=225, null=True),
        ),
    ]
