# Generated by Django 5.0.6 on 2024-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_newuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='admission_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
