# Generated by Django 5.0.6 on 2024-09-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_newuser_admission_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
