# Generated by Django 5.0.6 on 2024-09-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
