# Generated by Django 5.0.6 on 2024-09-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_coursegrade_schools'),
        ('users', '0020_alter_newuser_admission_no_alter_newuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_school', to='quiz.school'),
        ),
    ]
