# Generated by Django 5.0.6 on 2024-09-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_profile_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_school',
            new_name='schools',
        ),
    ]
