# Generated by Django 4.1 on 2024-03-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('quiz', '0003_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='completed_by',
            field=models.ManyToManyField(through='sms.CompletedTopics', to='users.profile'),
        ),
        migrations.AddField(
            model_name='topics',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='skillyouwillgain',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='categories',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='sms.categories'),
        ),
        migrations.AddField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='courselearnerreviews',
            name='courses_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courselearner', to='sms.courses'),
        ),
        migrations.AddField(
            model_name='coursefrequentlyaskquestions',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='completedtopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.topics'),
        ),
        migrations.AddField(
            model_name='completedtopics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='careeropportunities',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='sms.blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='aboutcourseowner',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
    ]
