# Generated by Django 5.0.6 on 2025-10-21 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_initial'),
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='courselearnerreviews',
            name='courses_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courselearner', to='sms.courses'),
        ),
        migrations.AddField(
            model_name='coursefrequentlyaskquestions',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='courses',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.examtype'),
        ),
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='courses',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='courses',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
    ]
