# Generated by Django 5.0.6 on 2025-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examtype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_examtype_per_school'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_term_per_school'),
        ),
    ]
