# Generated by Django 5.0.4 on 2024-04-20 21:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_carousel', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='carousel_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
