# Generated by Django 5.0.6 on 2025-10-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_examtype_unique_examtype_per_school_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examtype',
            name='unique_examtype_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_session_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_per_school',
        ),
    ]
