# Generated by Django 5.0.4 on 2024-04-20 22:28

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageVideo',
            fields=[
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
