# Generated by Django 5.0.6 on 2026-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_examtype_unique_examtype_per_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagevideo',
            name='video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
