# Generated by Django 5.0.6 on 2026-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_frontpagevideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_midterm',
            field=models.BooleanField(default=False),
        ),
    ]
