# Generated by Django 5.0.4 on 2024-04-21 11:49

import cloudinary.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='img_about_us',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_us'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
