# Generated by Django 5.0.4 on 2024-04-23 10:04

import cloudinary.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_aboutus_created_aboutus_img_about_us_aboutus_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('img_about_us', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_us')),
                ('content', tinymce.models.HTMLField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
