# Generated by Django 5.0.6 on 2026-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_term_is_midterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
