# Generated by Django 5.0.4 on 2024-04-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentlyaskquestions',
            name='course_type',
        ),
    ]
