# Generated by Django 5.0.4 on 2024-05-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_courses_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cert_price',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_logo',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_owner',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='status_type',
        ),
    ]
