# Generated by Django 5.0.4 on 2024-05-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_remove_courses_categories_remove_courses_cert_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='img_course',
        ),
    ]
