# Generated by Django 5.0.6 on 2024-07-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_delete_certificate_note_remove_resultassessment_exam_and_more'),
        ('sms', '0011_remove_courses_img_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcourseowner',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='careeropportunities',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='completedtopics',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='completedtopics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='completed_by',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.RemoveField(
            model_name='skillyouwillgain',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='whatyouwillbuild',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='whatyouwilllearn',
            name='courses',
        ),
        migrations.DeleteModel(
            name='AboutCourseOwner',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blogcomment',
        ),
        migrations.DeleteModel(
            name='CareerOpportunities',
        ),
        migrations.DeleteModel(
            name='CompletedTopics',
        ),
        migrations.DeleteModel(
            name='Skillyouwillgain',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='Whatyouwillbuild',
        ),
        migrations.DeleteModel(
            name='Whatyouwilllearn',
        ),
    ]
