# Generated by Django 5.0.6 on 2024-08-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_remove_aboutcourseowner_courses_delete_alert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
    ]
