# Generated by Django 5.0.6 on 2024-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_courses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
