# Generated by Django 5.0.6 on 2024-09-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_alter_result_result_class_alter_result_session_and_more'),
        ('sms', '0014_courses_session_courses_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
    ]
