# Generated by Django 5.0.6 on 2024-09-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_coursegrade_schools'),
        ('sms', '0016_session_term_alter_courses_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.examtype'),
        ),
    ]
