# Generated by Django 5.0.6 on 2025-06-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_initial'),
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('student_class', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('initial_total_deposit', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_deposit', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=10, null=True)),
                ('school_shop', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('caps', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('haircut', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
                ('total_expense', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=10)),
                ('balance_brought_forward', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('exhausted', 'Exhausted'), ('remaining', 'Remaining')], db_index=True, default='remaining', max_length=10)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financerecord', to='quiz.school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term')),
            ],
        ),
    ]
