# Generated by Django 5.0.6 on 2024-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('total_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school_shop', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('caps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('haircut', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_brought_forward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('exhausted', 'Exhausted'), ('remaining', 'Remaining')], default='remaining', max_length=10)),
            ],
        ),
    ]
