# Generated by Django 5.0.6 on 2026-09-12 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('quiz', '0024_school_junior_exam_score_school_junior_midterm_score_and_more'),
        ('sms', '0007_alter_term_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financerecord',
            options={'ordering': ['names', 'session', 'term__order', 'week_start', 'sn']},
        ),
        migrations.AddField(
            model_name='financerecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, help_text='Date this school week started (e.g. Monday).', null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='balance_brought_forward',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='names',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='student_class',
            field=models.CharField(blank=True, db_index=True, default='NA', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['school', 'session', 'term', 'names'], name='finance_fin_school__15568e_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['student', 'session', 'term'], name='finance_fin_student_260cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['school', 'week_start'], name='finance_fin_school__f4f650_idx'),
        ),
    ]
