# Generated by Django 5.0.6 on 2024-11-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financerecord_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='balance_brought_forward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
