# Generated by Django 5.0.6 on 2026-09-13 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financerecord_options_financerecord_student_and_more'),
        ('quiz', '0024_school_junior_exam_score_school_junior_midterm_score_and_more'),
        ('sms', '0007_alter_term_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['school', 'status'], name='finance_fin_school__eefd59_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['school', 'session', 'term', 'week_start'], name='finance_fin_school__798219_idx'),
        ),
        migrations.AddIndex(
            model_name='financerecord',
            index=models.Index(fields=['-sn'], name='finance_fin_sn_cb752c_idx'),
        ),
    ]
