# Generated by Django 5.0.6 on 2026-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financerecord_created_at_financerecord_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
