# Generated by Django 5.0.6 on 2024-11-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_financerecord_caps_alter_financerecord_haircut_and_more'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
    ]
