# Generated by Django 5.0.6 on 2024-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financerecord_session_financerecord_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='student_class',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
