# Generated by Django 5.0.6 on 2024-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financerecord_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='student_class',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
