# Generated by Django 5.0.6 on 2024-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_financerecord_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
