# Generated by Django 5.0.6 on 2024-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financerecord_initial_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
