# Generated by Django 5.0.6 on 2024-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_financerecord_initial_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
