# Generated by Django 5.0.6 on 2024-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_financerecord_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='balance_brought_forward',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
