# Generated by Django 5.0.6 on 2024-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_financerecord_balance_brought_forward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='balance_brought_forward',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='caps',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='current_balance',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='haircut',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='others',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='school_shop',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_expense',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=10),
        ),
    ]
