# Generated by Django 5.0.6 on 2024-11-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_financerecord_balance_brought_forward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='initial_total_deposit',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
