# Generated by Django 5.0.6 on 2024-11-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_financerecord_initial_total_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=10),
        ),
    ]
