# Generated by Django 5.0.6 on 2024-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_financerecord_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
