# Generated by Django 5.0.6 on 2024-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_financerecord_total_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='status',
            field=models.CharField(choices=[('exhausted', 'Exhausted'), ('remaining', 'Remaining')], db_index=True, default='remaining', max_length=10),
        ),
    ]
