# Generated by Django 5.0.6 on 2025-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_financerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='total_deposit',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
