# Generated by Django 4.1 on 2024-03-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsassessment',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.topics'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_name',
            field=models.ManyToManyField(blank=True, to='quiz.list_subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='subject_result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subjects'),
        ),
    ]
