# Generated by Django 5.0.6 on 2024-10-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
    ]
