# Generated by Django 5.0.6 on 2025-06-15 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_initial'),
        ('sms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='course_grade', to='quiz.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
        migrations.AddField(
            model_name='result',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseschool', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='examsrules',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examrules', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursegrade', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='quiz.school'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam', 'session', 'term', 'result_class', 'exam_type')},
        ),
    ]
