# Generated by Django 5.0.6 on 2025-10-21 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0002_initial'),
        ('sms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='course_grade', to='quiz.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.examtype'),
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='quiz_school_name_41941d_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_name'], name='quiz_school_school__b76263_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['course_pay'], name='quiz_school_course__c22452_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['customer'], name='quiz_school_custome_74ce27_idx'),
        ),
        migrations.AddField(
            model_name='result',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseschool', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursegrade', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.result'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam', 'session', 'term', 'result_class', 'exam_type')},
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['schools'], name='quiz_course_schools_bafadc_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['name'], name='quiz_course_name_34be33_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['is_active'], name='quiz_course_is_acti_e9baff_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['schools'], name='quiz_course_schools_5b5dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='quiz_course_course__73d637_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['session'], name='quiz_course_session_3d470c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term'], name='quiz_course_term_id_a35bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['exam_type'], name='quiz_course_exam_ty_c44a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsession',
            unique_together={('student', 'course')},
        ),
    ]
