# Generated by Django 5.0.6 on 2024-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='course_grade', to='sms.courses'),
        ),
    ]
