# Generated by Django 4.1 on 2024-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubject',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.ManyToManyField(blank=True, to='quiz.list_subjects')),
            ],
        ),
    ]
