# Generated by Django 5.0.6 on 2025-10-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
        ('sms', '0004_remove_examtype_unique_examtype_per_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.examtype'),
        ),
    ]
