# Generated by Django 5.0.6 on 2025-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsrules',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
