# Generated by Django 5.0.6 on 2025-06-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_examsrules_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsrules',
            old_name='schools',
            new_name='school_name',
        ),
    ]
