# Generated by Django 5.0.6 on 2024-10-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_coursegrade_subjects'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'session', 'term', 'schools')},
        ),
    ]
