# Generated by Django 4.1 on 2024-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_addsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='quiz.addsubject'),
        ),
    ]
