# Generated by Django 5.0.6 on 2025-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_result_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_ca_score',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum CA score', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='max_exam_score',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Maximum Exam score', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='max_midterm_score',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum Midterm score', max_digits=5),
        ),
    ]
