# Generated by Django 5.0.6 on 2025-06-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_schools_examsrules_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsrules',
            name='school_name',
        ),
    ]
