# Generated by Django 4.1 on 2024-03-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_group_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsubject',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addsubjects', to='quiz.school'),
        ),
    ]
