# Generated by Django 5.0.6 on 2025-11-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_school_max_ca_score_school_max_exam_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='max_ca_score',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Maximum CA score', max_digits=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='max_exam_score',
            field=models.DecimalField(decimal_places=1, default=60.0, help_text='Maximum Exam score', max_digits=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='max_midterm_score',
            field=models.DecimalField(decimal_places=1, default=30.0, help_text='Maximum Midterm score', max_digits=5),
        ),
    ]
