# Generated by Django 5.0.6 on 2025-06-27 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_result_result_class'),
        ('sms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='course_pay',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='customer',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['schools'], name='quiz_course_schools_5b5dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='quiz_course_course__73d637_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['session'], name='quiz_course_session_3d470c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term'], name='quiz_course_term_id_a35bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['exam_type'], name='quiz_course_exam_ty_c44a14_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['schools'], name='quiz_course_schools_bafadc_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['name'], name='quiz_course_name_34be33_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['is_active'], name='quiz_course_is_acti_e9baff_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='quiz_school_name_41941d_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_name'], name='quiz_school_school__b76263_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['course_pay'], name='quiz_school_course__c22452_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['customer'], name='quiz_school_custome_74ce27_idx'),
        ),
    ]
