# Generated by Django 4.1 on 2024-03-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_subject_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subjects'),
        ),
    ]
