# Generated by Django 5.0.6 on 2025-11-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_school_max_ca_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_active', models.BooleanField(default=False)),
                ('report_card_active', models.BooleanField(default=False)),
                ('cbt_expiry', models.DateField(blank=True, null=True)),
                ('report_card_expiry', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='quiz.school')),
            ],
        ),
    ]
