# Generated by Django 5.0.6 on 2025-11-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_schoolsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolSubscription',
        ),
    ]
