# Generated by Django 5.0.6 on 2025-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_studentexamsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_screen',
            field=models.BooleanField(default=False),
        ),
    ]
