# Generated by Django 4.1 on 2024-03-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_student_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
