# Generated by Django 5.0.6 on 2025-10-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_course_full_screen'),
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
    ]
