# Generated by Django 5.0.6 on 2025-10-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_coursegrade_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='session',
        ),
    ]
