# Generated by Django 5.0.6 on 2024-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='course_grade', to='quiz.course'),
        ),
    ]
