# Generated by Django 5.0.6 on 2025-11-23 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_generationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursegrade',
            name='quiz_course_schools_bafadc_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursegrade',
            name='quiz_course_name_34be33_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursegrade',
            name='quiz_course_is_acti_e9baff_idx',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='form_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
