# Generated by Django 4.1 on 2024-03-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        ('quiz', '0011_rename_student_user_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course_name',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
    ]
