# Generated by Django 5.0.6 on 2025-11-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_coursegrade_quiz_course_schools_bafadc_idx_and_more'),
        ('sms', '0004_remove_examtype_unique_examtype_per_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
    ]
