# Generated by Django 5.0.6 on 2025-11-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_coursegrade_session_coursegrade_term'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='form_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher_classes', to='teacher.teacher'),
        ),
    ]
