# Generated by Django 5.0.6 on 2024-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_coursegrade_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='course_grade', to='quiz.course'),
        ),
    ]
