# Generated by Django 4.1 on 2024-03-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_subjects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.list_subjects'),
        ),
    ]
