# Generated by Django 5.0.6 on 2025-05-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_coursegrade_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name__title'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
    ]
