# Generated by Django 4.1 on 2024-03-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_subjects_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='quiz.school'),
        ),
    ]
