# Generated by Django 5.0.6 on 2025-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_coursegrade_form_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fullscreencounter',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
