# Generated by Django 4.1 on 2024-03-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_course_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursegroups', to='quiz.course')),
            ],
        ),
    ]
