# Generated by Django 5.0.6 on 2025-05-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_question_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='school',
        ),
    ]
