# Generated by Django 5.0.6 on 2026-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_question_answer_alter_question_id_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='form_teacher',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='form_teacher',
            field=models.ManyToManyField(blank=True, related_name='form_teacher_classes', to='teacher.teacher'),
        ),
    ]
