# Generated by Django 4.1 on 2024-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_coursegrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='subjects',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='coursegrade', to='quiz.addsubject'),
        ),
    ]
