# Generated by Django 5.0.6 on 2025-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_result_tab_switch_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='result',
            name='tab_switch_count',
        ),
    ]
