# Generated by Django 4.1 on 2024-03-29 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_group_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='email',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
