# Generated by Django 5.0.6 on 2026-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='next_term_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
