# Generated by Django 5.0.6 on 2026-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_school_next_term_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='show_affective',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_form_teacher_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_position',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_principal_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='show_psychomotor',
            field=models.BooleanField(default=True),
        ),
    ]
