# Generated by Django 4.1 on 2024-03-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        ('quiz', '0019_remove_group_email_coursegrade_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='coursegrade', to='sms.courses'),
        ),
    ]
