# Generated by Django 4.1 on 2024-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_coursegrade_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_questions',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
