# Generated by Django 4.1 on 2024-04-01 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0021_course_show_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='email',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='students',
            field=models.ManyToManyField(related_name='course_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(related_name='course_grade', to='sms.courses'),
        ),
    ]
