# Generated by Django 4.1 on 2024-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_coursegrade_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='course_pay',
            field=models.BooleanField(default=False),
        ),
    ]
