# Generated by Django 5.0.6 on 2026-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_result_res_stu_ses_term_result_res_exam_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='junior_exam_score',
            field=models.DecimalField(decimal_places=1, default=60.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='junior_midterm_score',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='senior_exam_score',
            field=models.DecimalField(decimal_places=1, default=70.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='senior_midterm_score',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=5),
        ),
    ]
