# Generated by Django 5.0.6 on 2026-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_school_junior_exam_score_school_junior_midterm_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='course_grade', to='quiz.course'),
        ),
    ]
