# Generated by Django 4.1 on 2024-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_school_course_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pay',
            field=models.BooleanField(default=False),
        ),
    ]
