# Generated by Django 4.1 on 2024-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_course_course_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='customer',
            field=models.BooleanField(default=True),
        ),
    ]
