# Generated by Django 4.1 on 2024-04-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_school_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subject_question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject_result',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='subject_result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='schools',
        ),
        migrations.DeleteModel(
            name='AddSubject',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='List_Subjects',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject_Question',
        ),
        migrations.DeleteModel(
            name='Subject_Result',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
