# Generated by Django 5.0.4 on 2024-04-07 11:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_alter_question_answer_alter_question_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
