# Generated by Django 5.0.4 on 2024-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
