# Generated by Django 5.0.4 on 2024-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_course_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_attemps',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
