# Generated by Django 5.0.4 on 2024-05-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_course_num_attemps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img_partdesc1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='img_partdesc2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signby_portfolio',
        ),
    ]
