# Generated by Django 5.0.6 on 2024-06-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_remove_course_img_partdesc1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='coursegrade',
            options={'verbose_name': 'Student class', 'verbose_name_plural': 'student classes'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='pass_mark',
        ),
    ]
