# Generated by Django 5.0.6 on 2024-07-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_alter_course_options_alter_coursegrade_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate_note',
        ),
        migrations.RemoveField(
            model_name='resultassessment',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='resultassessment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='topicsassessment',
            name='course_name',
        ),
        migrations.DeleteModel(
            name='QuestionAssessment',
        ),
        migrations.DeleteModel(
            name='ResultAssessment',
        ),
        migrations.DeleteModel(
            name='TopicsAssessment',
        ),
    ]
