# Generated by Django 5.0.6 on 2024-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_delete_certificate_note_remove_resultassessment_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
