# Generated by Django 5.0.6 on 2024-08-10 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_alter_course_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='school_logos'),
        ),
    ]
