# Generated by Django 5.0.6 on 2024-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_coursegrade_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='logo',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='ai_question_num',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
