# Generated by Django 5.0.6 on 2024-08-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_remove_coursegrade_logo_coursegrade_ai_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='ai_question_num',
        ),
    ]
