# Generated by Django 5.0.6 on 2024-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_remove_coursegrade_ai_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_moto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
