# Generated by Django 5.0.6 on 2024-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_school_school_moto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_moto',
            new_name='school_motto',
        ),
        migrations.AddField(
            model_name='school',
            name='school_address',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
