# Generated by Django 5.0.6 on 2024-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_alter_result_result_class_alter_result_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
