# Generated by Django 5.0.6 on 2024-09-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_coursegrade_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursegrade', to='quiz.school'),
        ),
    ]
