# Generated by Django 5.0.6 on 2024-09-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_alter_course_session_alter_course_term_and_more'),
        ('sms', '0017_alter_courses_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.session'),
        ),
        migrations.AddField(
            model_name='question',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.term'),
        ),
    ]
