# Generated by Django 5.0.6 on 2024-10-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_question_exam_type_question_schools_question_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='term',
        ),
    ]
