# Generated by Django 5.0.6 on 2024-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0059_alter_result_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
