# Generated by Django 5.0.6 on 2026-04-29 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_course_course_name'),
        ('student', '0002_exameventlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exameventlog',
            old_name='exam',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='exameventlog',
            name='event_type',
            field=models.CharField(choices=[('exam_started', 'Exam Started'), ('auto_save', 'Auto Save'), ('power_outage', 'Power Outage'), ('exam_resumed', 'Exam Resumed'), ('exam_submitted', 'Exam Submitted'), ('heartbeat', 'Heartbeat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exameventlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds', models.IntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('resume_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course', 'is_submitted')},
            },
        ),
    ]
