# Generated by Django 5.0.4 on 2024-04-25 08:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('img_ebook', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery images')),
                ('price', models.DecimalField(blank=True, decimal_places=0, default='500', max_digits=10, max_length=225, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
