# Generated by Django 5.0.6 on 2026-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_exam_exameventlog_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='saved_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
