# Generated by Django 5.0.4 on 2024-04-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_pdfgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfgallery',
            name='price',
        ),
    ]
