# Generated by Django 5.0.6 on 2026-04-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_examattempt_saved_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
