# Generated by Django 5.0.4 on 2024-04-25 09:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_pdfgallery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('img_ebook', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='directors images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('img_ebook', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='management images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
