# Generated by Django 5.0.6 on 2026-04-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_examattempt_tab_switch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='blur_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='screenshot_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
