# Generated by Django 5.0.6 on 2024-06-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_directors_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
