# Generated by Django 5.0.6 on 2026-05-01 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_result_res_stu_ses_term_result_res_exam_marks_and_more'),
        ('student', '0006_examattempt_blur_count_examattempt_screenshot_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'is_submitted'], name='idx_attempt_student_active'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['resume_code'], name='idx_attempt_resume_code'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['course', 'is_submitted'], name='idx_attempt_course_active'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['start_time'], name='idx_attempt_start_time'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'course', 'is_submitted'], name='idx_attempt_unique_key'),
        ),
        migrations.AddIndex(
            model_name='exameventlog',
            index=models.Index(fields=['student', 'timestamp'], name='student_exa_student_42986f_idx'),
        ),
        migrations.AddIndex(
            model_name='exameventlog',
            index=models.Index(fields=['course', 'event_type'], name='student_exa_course__facf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='exameventlog',
            index=models.Index(fields=['timestamp'], name='student_exa_timesta_1fb0df_idx'),
        ),
    ]
