# Generated by Django 5.0.6 on 2026-05-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_examattempt_idx_attempt_student_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
    ]
