# Generated by Django 5.0.6 on 2024-09-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_course_session_course_term'),
        ('student', '0008_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
