# Generated by Django 5.0.6 on 2024-09-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_badge_result_badge_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='course',
        ),
    ]
