# Generated by Django 5.0.6 on 2024-09-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_badge_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='session',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='term',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
