# Generated by Django 5.0.6 on 2024-09-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_badge_session_badge_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_type',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
    ]
