# Generated by Django 5.0.6 on 2024-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_badge_badge_type_remove_badge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
