# Generated by Django 5.0.6 on 2024-09-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_badge_badge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='final_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='final_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
