# Generated by Django 5.0.6 on 2024-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_badge_final_average_badge_final_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badge_description',
            new_name='badge_type',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
