# Generated by Django 5.0.6 on 2024-09-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_badgedownloadstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgedownloadstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='badgedownloadstats',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badgedownloadstats',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.badge'),
        ),
        migrations.AlterField(
            model_name='badgedownloadstats',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badgedownloadstats',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='badgedownloadstats',
            unique_together={('student', 'badge', 'school', 'month', 'year')},
        ),
    ]
