# Generated by Django 5.0.6 on 2024-09-24 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_alter_result_result_class_alter_result_session_and_more'),
        ('student', '0019_alter_badgedownloadstats_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgedownloadstats',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='badgedownloadstats',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.school'),
        ),
        migrations.AlterField(
            model_name='badgedownloadstats',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='badgedownloadstats',
            unique_together={('badge', 'school', 'month', 'year')},
        ),
    ]
