# Generated by Django 5.0.6 on 2024-09-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_alter_result_result_class_alter_result_session_and_more'),
        ('student', '0020_alter_badgedownloadstats_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgedownloadstats',
            unique_together={('school', 'badge', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='badgedownloadstats',
            name='student',
        ),
    ]
