# Generated by Django 5.0.6 on 2024-09-24 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_alter_result_result_class_alter_result_session_and_more'),
        ('student', '0021_alter_badgedownloadstats_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exams_conducted', models.PositiveIntegerField(default=0)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.school')),
            ],
        ),
    ]
