# Generated by Django 5.0.6 on 2024-11-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('quiz', '0013_alter_coursegrade_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconduct',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducts', to='quiz.coursegrade'),
        ),
    ]
