# Generated by Django 5.0.6 on 2024-11-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_studentconduct_options_and_more'),
        ('sms', '0002_alter_term_options_term_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentconduct',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='studentconduct',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducts', to='sms.session'),
        ),
        migrations.AddField(
            model_name='studentconduct',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducts', to='sms.term'),
        ),
    ]
