# Generated by Django 5.0.6 on 2024-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studentconduct_options_studentconduct_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconduct',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
